baseURL = "https://patrolli.github.io/xssq/"
languageCode = "en"
defaultContentLanguage = "en"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "patrolli"
canonifyURLs = true
publishDir = "docs"
theme = "hugo-onyx-theme"
summaryLength = 20


enableEmoji = true
disableFastRender = true        # Hugo 0.30
# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsCodefences = true
pygmentsUseClasses = true

[Author]
  name = "patrolli"

[params]
  name = "Onyx"
  description = "A Hugo theme built using the Hugo Alabaster theme as base."

  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  dateform = "Mon Jan 2, 2006"



[params.sidebar]
  logo = "favicon.ico"

  github_button  = false
  travis_button  = false
  codecov_button = false
  gratipay = ""

  # Mon Sep 04 23:55:36 EDT 2017 - kmodi
  # Disable this option for now.. but seems to be useful in future
  show_relations = false

[params.footer]
  copyright = ""
  show_powered_by = true
