baseURL = "https://patrolli.github.io/xssq/"
languageCode = "en"
defaultContentLanguage = "en"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "patrolli"
canonifyURLs = true
publishDir = "docs"
theme = "ananke"
summaryLength = 20

[languages.en]
  languageCode = "zh-cn"

[author]                  # essential                     # 必需
  name = "patrolli"

[params]
  toc = true

[[menu.main]]             # config your menu              # 配置目录
  name = "This is Home"
  weight = 10
  identifier = "home"
  url = "/xssq/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/xssq/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/xssq/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/xssq/categories/"