baseURL = "https://patrolli.github.io/xssq/"
languageCode = "en"
defaultContentLanguage = "en"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "patrolli"
canonifyURLs = true
publishDir = "docs"
theme = "maupassant"
summaryLength = 20
[params]
  author = "patrolli"
  toc = true


[markup]
  [markup.highlight]
    lineNos = false
    style = "github"

# [menu]

#   [[menu.main]]
#     identifier = "tools"
#     name = "工具"
#     url = "/tools/"
#     weight = 2

#   [[menu.main]]
#     identifier = "archives"
#     name = "归档"
#     url = "/archives/"
#     weight = 3

#   [[menu.main]]
#     identifier = "about"
#     name = "关于"
#     url = "/about/"
#     weight = 4