baseURL = "https://patrolli.github.io/xssq/"
languageCode = "en"
defaultContentLanguage = "en"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "LiXunsong's blog"

publishDir = "docs"
theme = "maupassant"
